//  CREATE
export 'package:noveles/features/domain/use_cases/create_book.dart';
export 'package:noveles/features/domain/use_cases/create_chapter.dart';
export 'package:noveles/features/domain/use_cases/create_genre.dart';
export 'package:noveles/features/domain/use_cases/create_took.dart';
export 'package:noveles/features/domain/use_cases/delete_book.dart';
//  DELETE
export 'package:noveles/features/domain/use_cases/delete_chapter.dart';
export 'package:noveles/features/domain/use_cases/delete_genre.dart';
export 'package:noveles/features/domain/use_cases/delete_took.dart';
export 'package:noveles/features/domain/use_cases/get_book.dart';
export 'package:noveles/features/domain/use_cases/get_book_by_id.dart';
export 'package:noveles/features/domain/use_cases/get_chapter.dart';
//  GET_BY_ID
export 'package:noveles/features/domain/use_cases/get_chapter_by_id.dart';
export 'package:noveles/features/domain/use_cases/get_genre.dart';
export 'package:noveles/features/domain/use_cases/get_genre_by_id.dart';
export 'package:noveles/features/domain/use_cases/get_took.dart';
export 'package:noveles/features/domain/use_cases/get_took_by_id.dart';
export 'package:noveles/features/domain/use_cases/update_book.dart';
//  UPDATE
export 'package:noveles/features/domain/use_cases/update_chapter.dart';
export 'package:noveles/features/domain/use_cases/update_genre.dart';
export 'package:noveles/features/domain/use_cases/update_took.dart';
//  AUTH
export 'package:noveles/features/domain/use_cases/login.dart';
export 'package:noveles/features/domain/use_cases/register.dart';
export 'package:noveles/features/domain/use_cases/logout.dart';
export 'package:noveles/features/domain/use_cases/get_current_user.dart';
//  PROFILE
export 'package:noveles/features/domain/use_cases/get_profile.dart';
export 'package:noveles/features/domain/use_cases/update_profile.dart';
export 'package:noveles/features/domain/use_cases/upload_avatar.dart';
export 'package:noveles/features/domain/use_cases/upload_cover.dart';
export 'package:noveles/features/domain/use_cases/change_password.dart';
export 'package:noveles/features/domain/use_cases/get_chapter_content.dart';
export 'package:noveles/features/domain/use_cases/get_books_by_genre.dart';
export 'package:noveles/features/domain/use_cases/toggle_book_visibility.dart';
