name: noveles
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI / COMPONENTES VISUALES
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^4.2.1
  expandable: ^5.0.1
  dropdown_button2: ^2.3.9

  # ARQUITECTURA / STATE MANAGEMENT
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # ALMACENAMIENTO / PERSISTENCIA
  shared_preferences: ^2.3.1
  path_provider: ^2.1.4

  # Dependency Injection
  get_it: ^7.6.0
  injectable: ^2.3.2
  dartz: ^0.10.1

  # OTROS
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/book/
    - assets/book/ch/
    - assets/book/cr/
    - assets/book/cr/sl/
    - assets/book/eu/
    - assets/book/eu/rwtss/
    - assets/book/jp/
    - assets/book/jp/oskar/
    - assets/cover/
    - assets/cover/ch/
    - assets/cover/cr/
    - assets/cover/eu/
    - assets/cover/jp/
    - assets/svg/
