name: noveles
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI / COMPONENTES VISUALES
  cupertino_icons: ^1.0.8
  carousel_slider: ^4.2.1

  # ARQUITECTURA / STATE MANAGEMENT
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # ALMACENAMIENTO / PERSISTENCIA


  # Dependency Injection
  get_it: ^7.6.0

  # SUPABASE
  supabase_flutter: ^2.10.0

  # IMAGE PICKER
  image_picker: ^1.1.2

  # OTROS
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/book/
    - assets/book/ch/
    - assets/book/cr/
    - assets/book/cr/sl/
    - assets/book/eu/
    - assets/book/eu/rwtss/
    - assets/book/jp/
    - assets/book/jp/oskar/
    - assets/cover/
    - assets/cover/ch/
    - assets/cover/cr/
    - assets/cover/eu/
    - assets/cover/jp/
