-- Labels system for admin editorial role
CREATE TABLE IF NOT EXISTS public.labels (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  name TEXT NOT NULL,
  color TEXT NOT NULL DEFAULT '#71A202'
);

CREATE TABLE IF NOT EXISTS public.books_labels (
  book_id BIGINT NOT NULL REFERENCES public.books(id) ON DELETE CASCADE,
  label_id BIGINT NOT NULL REFERENCES public.labels(id) ON DELETE CASCADE,
  PRIMARY KEY (book_id, label_id)
);

ALTER TABLE labels ENABLE ROW LEVEL SECURITY;
ALTER TABLE books_labels ENABLE ROW LEVEL SECURITY;

-- Labels policies
DROP POLICY IF EXISTS "Enable read for all users" ON labels;
CREATE POLICY "Enable read for all users" ON labels FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable insert for scan and admin" ON labels;
CREATE POLICY "Enable insert for scan and admin" ON labels FOR INSERT WITH CHECK (public.is_scan() OR public.is_admin());
DROP POLICY IF EXISTS "Enable update for scan and admin" ON labels;
CREATE POLICY "Enable update for scan and admin" ON labels FOR UPDATE USING (public.is_scan() OR public.is_admin());
DROP POLICY IF EXISTS "Enable delete for scan and admin" ON labels;
CREATE POLICY "Enable delete for scan and admin" ON labels FOR DELETE USING (public.is_scan() OR public.is_admin());

DROP POLICY IF EXISTS "Enable read for all users" ON books_labels;
CREATE POLICY "Enable read for all users" ON books_labels FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable insert for scan and admin" ON books_labels;
CREATE POLICY "Enable insert for scan and admin" ON books_labels FOR INSERT WITH CHECK (public.is_scan() OR public.is_admin());
DROP POLICY IF EXISTS "Enable delete for scan and admin" ON books_labels;
CREATE POLICY "Enable delete for scan and admin" ON books_labels FOR DELETE USING (public.is_scan() OR public.is_admin());
