-- ============================================================
-- Audit Plan Fixes — Migration
-- ============================================================
-- 1. Add autoincrement to genres.id (was plain INT PRIMARY KEY)
-- 2. Set books.author_id FK to ON DELETE SET NULL
-- ============================================================

-- STEP 1: genres.id autoincrement
-- genres table was created with INT PRIMARY KEY (no sequence).
-- Seed data has ids 0-19. Adding GENERATED BY DEFAULT preserves existing ids
-- while allowing new inserts to omit id and get auto-generated values.
ALTER TABLE genres ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Seed data has ids 0-19. Set sequence to start at 20 to avoid conflicts.
SELECT setval('genres_id_seq', GREATEST((SELECT COALESCE(MAX(id), 0) + 1 FROM genres), 1));


-- STEP 2: books.author_id ON DELETE SET NULL
-- The FK books.author_id -> authors(id) has NO ACTION (default).
-- Deleting an author with existing books would fail with FK violation.
-- SET NULL allows author deletion without cascading book deletion.
ALTER TABLE books DROP CONSTRAINT IF EXISTS books_author_id_fkey,
  ADD FOREIGN KEY (author_id) REFERENCES authors(id) ON DELETE SET NULL;
